name: Upload To Azure Blob Storage
on:
  push:
    branches:
      - master
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: mkdir -p path/to/artifact
      - run: echo hello > path/to/artifact/world.txt
      - uses: fixpoint/azblob-upload-artifact@v4        
        with:
          connection-string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          name: index.html
          path: path/to/artifact
